apimServiceName: apim-pktmtbrc-prod
namedValues:
  - name: Logger-Credentials
    properties:
      displayName: Logger-Credentials
      keyVault:
        secretIdentifier: "https://kv-pktmtbrc-prod.vault.azure.net/secrets/kvs-aikey"
loggers:
  # the name of the logger has to match the folder name in apimartifacts/loggers.
  # the folder name originally matches the dev instance's extracted logger name, but was renamed to a generic one
  - name: applicationinsights
    properties:
      resourceId: "/subscriptions/{SUBSCRIPTION_ID}/resourceGroups/rg-pktmtbrc-prod/providers/Microsoft.Insights/components/ai-pktmtbrc-prod"
      credentials:
        instrumentationKey: "{{Logger-Credentials}}"
diagnostics:
  - name: applicationinsights
    properties:
      verbosity: Error
      # loggerId must match the name of the logger above, in this case applicationinsights
      loggerId: "/subscriptions/{SUBSCRIPTION_ID}/resourceGroups/rg-pktmtbrc-prod/providers/Microsoft.ApiManagement/service/apim-pktmtbrc-prod/loggers/applicationinsights"
apis:
  - name: swagger-petstore
    properties:
      apiVersionSetId: "/subscriptions/{SUBSCRIPTION_ID}/resourceGroups/rg-pktmtbrc-prod/providers/Microsoft.ApiManagement/service/apim-pktmtbrc-prod/apiVersionSets/swagger-petstore" 
  - name: swagger-petstore-v2
    properties:
      apiVersionSetId: "/subscriptions/{SUBSCRIPTION_ID}/resourceGroups/rg-pktmtbrc-prod/providers/Microsoft.ApiManagement/service/apim-pktmtbrc-prod/apiVersionSets/swagger-petstore" 
  - name: swagger-petstore-v3
    properties:
      apiVersionSetId: "/subscriptions/{SUBSCRIPTION_ID}/resourceGroups/rg-pktmtbrc-prod/providers/Microsoft.ApiManagement/service/apim-pktmtbrc-prod/apiVersionSets/swagger-petstore" 
  - name: swagger-petstore-v3;rev=2
    properties:
      apiVersionSetId: "/subscriptions/{SUBSCRIPTION_ID}/resourceGroups/rg-pktmtbrc-prod/providers/Microsoft.ApiManagement/service/apim-pktmtbrc-prod/apiVersionSets/swagger-petstore" 