---
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
paths:
  /version:
    get:
      tags:
        - api-controller
      operationId: getVersion
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /mirror-name:
    get:
      tags:
        - api-controller
      operationId: mirrorName
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /health:
    get:
      tags:
        - api-controller
      operationId: healthCheck
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components: {}