apimServiceName: ${DEV_APIM_NAME}
backends:
  - name: swagger-petstore
    properties:
      url: "https://petstore.swagger.io/v2"
apis:
  - name: swagger-petstore
    properties:
      displayName: "Swagger Petstore V1"
      apiVersionSetId: "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${DEV_RESOURCE_GROUP_NAME}/providers/Microsoft.ApiManagement/service/${DEV_APIM_NAME}/apiVersionSets/swagger-petstore" 
  - name: swagger-petstore-v2
    properties:
      displayName: "Swagger Petstore V2"
      apiVersionSetId: "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${DEV_RESOURCE_GROUP_NAME}/providers/Microsoft.ApiManagement/service/${DEV_APIM_NAME}/apiVersionSets/swagger-petstore" 
  - name: swagger-petstore-v3
    properties:
      displayName: "Swagger Petstore V3"
      apiVersionSetId: "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${DEV_RESOURCE_GROUP_NAME}/providers/Microsoft.ApiManagement/service/${DEV_APIM_NAME}/apiVersionSets/swagger-petstore"  