---
ingress:
  enabled: true
  hosts:
    - host: apim-be-dev.gc.bartbase.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: gc-bartbase
      hosts:
        - apim-be-dev.gc.bartbase.com
